services:
  rhiva-ag:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
      - "8000-8005:8000-8005"
    networks:
      - webnet
    env_file: .env
networks:
  webnet:
    driver: bridge
    external: true