services:
  trpc:
    image: rhive-ag_trpc:latest
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: "0.5"
        limits:
          cpus: "1.0"
    networks:
      - webnet
      - redis
    env_file: .env

  tasks:
    image: rhive-ag_tasks:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: "0.5"
        limits:
          cpus: "1.0"
    networks:
      - redis
    env_file: .env

  jobs:
    image: rhive-ag_jobs:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: "0.5"
        limits:
          cpus: "1.0"
    depends_on:
      - tasks
    networks:
      - redis
    env_file: .env

  metrics:
    image: rhive-ag_metrics:latest
    ports:
      - "8001:8001"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: "0.5"
        limits:
          cpus: "1.0"
    depends_on:
      - tasks
    networks:
      - redis
    environment:
      PORT: 8001
    env_file: .env

networks:
  webnet:
    driver: overlay
  redis:
    driver: overlay
    external: true
