services:
  trpc:
    build:
      context: .
      target: api
    ports:
      - "8000:8000"
    deploy:
      restart_policy: 
        condition: on-failure
    restart: unless-stopped
    networks:
      - webnet
      - redis
    env_file: .env
  tasks:
    build:
      context: .
      target: tasks
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
    restart: unless-stopped
    networks:
      - redis
  jobs:
    build:
      context: .
      target: jobs
    deploy:
      replicas: 2
      restart_policy: 
        condition: on-failure
    restart: unless-stopped
    depends_on: 
      - tasks 
    networks:
      - redis
  
networks:
  webnet:
    driver: bridge
  redis: 
    external: true 
