services:
  trpc:
    build:
      context: .
      target: trpc
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      resources:
        reservations:
          cpus: "0.5"
        limits:
          cpus: "1.0"
    restart: unless-stopped
    networks:
      - webnet
      - redis
    env_file: .env
    
  tasks:
    build:
      context: .
      target: tasks
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      resources:
        reservations:
          cpus: "0.5"
        limits:
          cpus: "1.0"
    restart: unless-stopped
    networks:
      - redis
    env_file: .env
    
  jobs:
    build:
      context: .
      target: jobs
    deploy:
      replicas: 2
      restart_policy: 
        condition: on-failure
      resources:
        reservations:
          cpus: "0.5"
        limits:
          cpus: "1.0"
    restart: unless-stopped
    depends_on: 
      - tasks 
    networks:
      - redis
    env_file: .env
networks:
  webnet:
    driver: bridge
  redis: 
    external: true 
