services:
  rhiva-ag:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "${PORT}:${PORT}"
      - "8000-8005:8000-8005"
    networks:
      - webnet
    env_file: .env
    environment:
      REDIS_URL: ${REDIS_URL}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--save",
        "900",
        "1",
        "--save",
        "300",
        "10",
        "--save",
        "60",
        "10000",
        "--replica-read-only",
        "no",
      ]
    networks:
      - webnet
    volumes:
      - redis-data:/data

networks:
  webnet:
    driver: bridge
    external: true
volumes:
  redis-data:
    external: true